name: Pipeline com Docker, Testes de Segurança e Envio de Mensagem para o Telegram
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Instalar dependências do NPM
      run: |
        npm install

    - name: Build da imagem Docker
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: true
        tags: your-docker-username/your-docker-image-name:latest

    - name: Testes de segurança
      uses: docker://owasp/zap2docker-stable
      with:
        entrypoint: zap-baseline.py
        target: http://your-web-app-url
        report: true
        reportfilename: owasp-zap-report.html

    - name: Enviar mensagem para o Telegram
      uses: appleboy/telegram-action@v0.2.0
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: "A pipeline foi executada com sucesso!" 
